### ISSUE TITLE
Create Binary Release 

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe-modeler#1]
Create a Release which users can download

**Comment by saig0** [comment]
@dominikhrn, where can I find the binaries of the release? I want to try it out ;-)

**Comment by dominikhrn** [comment]
@saig0 Thought the zip download is what you want. Where should I upload the files?

**Comment by saig0** [comment]
@dominikhrn , you can add the ZIP file to the release: https://github.com/zeebe-io/zeebe-modeler/releases/tag/0.1.0

**Comment by dominikhrn** [comment]
You are right... Thought it isn't possible because of the file size but there is a separate button

**Comment by dominikhrn** [comment]
Have a try ;)
