### ISSUE TITLE
Third Party summary mail has wrong release version

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#103]
__Describe the Bug__

The Mail we send out after each successful release creation does currently have a wrong release version. After we shipped `v0.7.0-alpha.1` release, there was still the old `v0.6.2` release included in the mail

![image](https://user-images.githubusercontent.com/9433996/64676516-0bc1f200-d476-11e9-82d8-4374c20ae235.png)

__Steps to Reproduce__

1. See Mail screenshot

__Expected Behavior__

Use correct version in [Third-party summary e-mail](https://github.com/zeebe-io/zeebe-modeler/blob/develop/tasks/send-license-book-summary.js#L225)

__Additional context__

It seems to work perfectly fine in the Camunda Modeler Releases.

**Comment by barmac** [comment]
This might be helpful:
https://stackoverflow.com/questions/4154485/git-describe-ignores-a-tag/4154518#4154518

**Comment by pinussilvestrus** [comment]
It came clear the tag really doesn't was annotated. It's because we had to manually create it because travis didn't start the publishing after `npm run release`. In this step, we simply forgot to annotate it (`-a`). So no work needs to be done here.
