### ISSUE TITLE
Event labels provide context menu

### ISSUE THREAD

**Issue by mschoe** [zeebe-io/zeebe-modeler#104]
__Describe the Bug__

__Steps to Reproduce__

// when
I click on an event label

// then
a context menu appears

![zeebe_modeler_label_context](https://user-images.githubusercontent.com/2777965/65412450-8cc2a700-ddef-11e9-8efc-a456498c8913.png)

__Expected Behavior__

no context menu appears

__Environment__

 - OS: linux
 - Zeeber Modeler Version: 0.7.0-alpha2

**Comment by oguzeroglu** [comment]
Closed via #106

**Comment by pinussilvestrus** [comment]
Let's not close this until we release it.  We do it all the time with bug fixes, and add the 'fixed upstream' label instead.
