### ISSUE TITLE
Add Support for Non-Execution-Relevant BPMN Symbols

### ISSUE THREAD

**Issue by philippfromme** [zeebe-io/zeebe-modeler#112]
__Is your feature request related to a problem? Please describe.__

There are lots of BPMN symbols missing in the Modeler, which have no execution semantics, but should be available to model anyway (e.g. for documentation purpose).

__Describe the solution you'd like__

Add support for following BPMN symbols

* [x] Annotations (cf. #114) 
* [x] Groups (cf. #113)
* [x] Lanes (cf. #114)
* [x] Message Flow (cf. #113)
* [x] Participants (cf. #113)

__Describe alternatives you've considered__

/

---

Related to https://app.prodpad.com/ideas/257/canvas.
Depends on #113 
Depends on #114

**Comment by pinussilvestrus** [comment]
That should be covered by #113, #114, #115, right? Maybe let's do these things first and then check whether all elements are supported, or do additional work if not.

**Comment by pinussilvestrus** [comment]
The support of these elements will probably be added by #113 and #114.

**Comment by pinussilvestrus** [comment]
Closed via #113 and #114
