### ISSUE TITLE
Align Palette with Camunda Modeler Palette

### ISSUE THREAD

**Issue by philippfromme** [zeebe-io/zeebe-modeler#113]
__Is your feature request related to a problem? Please describe.__

Currently, the Palette looks different/inconsistent with the Camunda Modeler Palette.

**Zeebe Modeler**

<img src="https://user-images.githubusercontent.com/9433996/66460157-a19d6c80-ea76-11e9-828a-928de9915c21.png" height=250 />

**Camunda Modeler**

<img src="https://user-images.githubusercontent.com/9433996/66460140-9ba78b80-ea76-11e9-8c2a-461cfe46aba6.png" height=250 />

__Describe the solution you'd like__

It should have the same palette items and order as the Camunda Modeler, **except** from following elements

* DataObject
* DataStore

__Describe alternatives you've considered__

/

---

Related to https://app.prodpad.com/ideas/253/canvas.

**Comment by pinussilvestrus** [comment]
To clarify: Are the users allowed to model anything? If yes, removing the custom provider should do the trick here. We will clarify that in the kick-off meeting.

**Comment by oguzeroglu** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/123
