### ISSUE TITLE
Align Context Pad with Camunda Modeler Context Pad

### ISSUE THREAD

**Issue by philippfromme** [zeebe-io/zeebe-modeler#114]
__Is your feature request related to a problem? Please describe.__

Currently, the ContextPad looks different/inconsistent with the Camunda Modeler ContextPad.

**Zeebe Modeler**

<img src="https://user-images.githubusercontent.com/9433996/66460727-cc3bf500-ea77-11e9-984e-3c911c0385a1.png" height=150 />

**Camunda Modeler**

<img src="https://user-images.githubusercontent.com/9433996/66460746-d4943000-ea77-11e9-9647-7f14b2f9f38a.png" height=150 />

__Describe the solution you'd like__

It should have the same context pad items and order as the Camunda Modeler.

__Describe alternatives you've considered__

/

---

Related to https://app.prodpad.com/ideas/253/canvas.

**Comment by pinussilvestrus** [comment]
To clarify: Are the users allowed to model anything? If yes, removing the custom provider should do the trick here. We will clarify that in the kick-off meeting.

**Comment by pinussilvestrus** [comment]
Seems like in this case we could simply remove the `CustomContextPadProvider` to align. No need for filtering anymore.

**Comment by pinussilvestrus** [comment]
We can't simply remove the `CustomContextPadProvider`, since we have to be aware of zeebe related modeling restrictions, cf. https://github.com/zeebe-io/zeebe-modeler/issues/29

**Comment by pinussilvestrus** [comment]
Closed via 642becba19a53aca874d287d06d9398caea0396f
