### ISSUE TITLE
Add All Replace Options to Context Pad

### ISSUE THREAD

**Issue by philippfromme** [zeebe-io/zeebe-modeler#115]
__Is your feature request related to a problem? Please describe.__

Currently, it's not possible to switch between all available types of tasks, events, gateways. E.g. it's not possible to switch back to blank tasks or blank intermediate events:

![image](https://user-images.githubusercontent.com/9433996/66483249-ff48ad80-eaa4-11e9-8982-bead6ed62b7c.png)

![image](https://user-images.githubusercontent.com/9433996/66483274-0cfe3300-eaa5-11e9-86e1-007846f8ad65.png)

__Describe the solution you'd like__

Enable all replace type combinations in the ReplaceMenu.

__Describe alternatives you've considered__

/

__Additional context__

---

Related to https://app.prodpad.com/ideas/255/canvas.

**Comment by pinussilvestrus** [comment]
To clarify: Are the users allowed to model anything? If yes, removing the custom provider should do the trick here. We will clarify that in the kick-off meeting.
