### ISSUE TITLE
Align Properties Panel with Camunda Modeler Properties Panel

### ISSUE THREAD

**Issue by philippfromme** [zeebe-io/zeebe-modeler#116]
__Is your feature request related to a problem? Please describe.__

The Zeebe Modeler properties panel is very inconsistent compared to the Camunda Modeler. For example, we have message related properties in the 'General' group. It should be in the 'Details' group.

<img src="https://user-images.githubusercontent.com/9433996/66292596-f7daa600-e8e4-11e9-960c-08231ca7078b.png" height=400 />

__Describe the solution you'd like__

Have only 'Id', 'Name', and 'Executable' in the General section and anything else in the 'Details' section.

__Describe alternatives you've considered__

/

__Additional context__

- [`ZeebePropertiesProvider`](https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js#L69)

---

Related to https://app.prodpad.com/ideas/256/canvas.

**Comment by pinussilvestrus** [comment]
Closed via b05822c5374e7ce3bc2d34f804652ca84d4dcedb
