### ISSUE TITLE
Please make the Modeler run as web app

### ISSUE THREAD

**Issue by mingfang** [zeebe-io/zeebe-modeler#127]
Currently the Modeler runs as a desktop app.
Please remove that limitation and make Modeler run as a web app.

**Comment by pinussilvestrus** [comment]
This application is meant to be built as desktop application (via electron). There are no plans to offer a web app. 

Since the Modeler is built on top of [`bpmn-io`](https://bpmn.io), one can easily do it himself. Feel free. But I don't think we will offer anything like this soon.

**Comment by philippfromme** [comment]
The Zeebe Modeler (and Camunda Modeler) is powered by the [bpmn.io toolkit](https://bpmn.io) which is embeddable by design. Here's an example of a web app: https://codesandbox.io/s/bpmn-js-custom-modeler-senuf
