### ISSUE TITLE
Improve CallActivity properties handling

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#130]
__Is your feature request related to a problem? Please describe.__

Introducing with #118 we will have two separated properties for `bpmn:CallActivity` elements (`processId`, `processIdExpression`). These are intended to be _exclusive_, which means only one input should be available.

We should investigate how we can deal with that.

![image](https://user-images.githubusercontent.com/9433996/66990050-c3759f80-f0c5-11e9-896b-b01f470cdf7d.png)

__Describe the solution you'd like__

Find a way for better handling so _only one_ property will be available to input. This could look like having

* a dropdown selection
* a detection which kind on input is declared (expression vs. normal string)
* some descriptions around the input fields to clarify the behavior

The properties provider should then detect which property is declared and accordingly serialize it to the `zeebe:CalledElement` property.

__Additional context__

Related to https://app.prodpad.com/ideas/271/canvas

**Comment by pinussilvestrus** [comment]
We came up with the decision to remove the `processIdExpression` by now.

**Comment by oguzeroglu** [comment]
Closed via #143
