### ISSUE TITLE
How to write a plugin?

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-modeler#137]
How do I write a plugin for the modeler? Is it possible?

I have a few things that I want to do - starting with uploading a BPMN diagram to the broker.

**Comment by nikku** [comment]
You write a plug-in in the same way you write plug-ins for the Camunda Modeler.

I suggest you to [checkout my talk about Camunda Con](https://github.com/nikku/camunda-modeler-plugins-talk-2019) or the list of [existing Camunda Modeler plug-ins](https://github.com/camunda/camunda-modeler-plugins) for inspiration.
