### ISSUE TITLE
Not supported output mapping on end events

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-modeler#138]
__Describe the Bug__

* on an end event, I can add "payload mappings" which are not supported by Zeebe anymore

```xml
    <bpmn:endEvent id="EndEvent_1ng8o4b">
      <bpmn:extensionElements>
        <zeebe:payloadMappings>
          <zeebe:mapping source="sourceValue" target="targetValue" type="PUT" />
        </zeebe:payloadMappings>
      </bpmn:extensionElements>
      <bpmn:incoming>SequenceFlow_0vltuqu</bpmn:incoming>
    </bpmn:endEvent>
```

__Steps to Reproduce__

1. add an end event
2. go to Properties Panel -> Payload Mappings
3. add a new input parameter

__Expected Behavior__

* I can not add "Payload Mapping" on an end event

__Environment__

 - OS: Ubuntu
 - Zeeber Modeler Version: 0.7.0

**Comment by pinussilvestrus** [comment]
Since the `Payload Mapping` tab was only related to `bpmn:EndEvents`, we can simply remove it.
