### ISSUE TITLE
New outputBehavior attribute on ioMapping

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-modeler#14]
It is now possible to change the default output behavior of the output mapping via the `outputBehavior` attribute on the `<ioMapping>` tag.
The `outputBehavior` can take three different states: `NONE`, `MERGE`, `OVERWRITE`.

For more information see the [documentation on stage](https://stage.docs.zeebe.io/bpmn-workflows/tasks.html) or the related issues https://github.com/zeebe-io/zeebe/issues/911, https://github.com/zeebe-io/zeebe/issues/908.

It should be possible to configure this behavior in the properties panel.

**Comment by dominikhrn** [comment]
@Zelldon I created a new release

**Comment by Zelldon** [comment]
Awesome thank you :tada:

**Comment by dominikhrn** [comment]
@Zelldon had to fix the selectBox. It didn't used the empty outputBehavior by default. That was confusing because the shown behavior "MERGE" wasn't saved in xml. Bug is fixed. Uploaded a new release. :)
