### ISSUE TITLE
Documentation for zeebe modeller shows 404 not found

### ISSUE THREAD

**Issue by tvvignesh** [zeebe-io/zeebe-modeler#140]
Hi. The URL https://docs.zeebe.io/bpmn-modeler/README.html which the modeller is pointing to in Help->Documentation as well as mentioned here https://github.com/zeebe-io/zeebe-modeler/issues/3 is not found.

![Screenshot from 2019-11-09 19-39-18](https://user-images.githubusercontent.com/1165845/68529820-a5980500-0328-11ea-801c-93dd0e85f632.png)

**Comment by nikku** [comment]
@zeebe-io/core Did the documentation move?

**Comment by pinussilvestrus** [comment]
Maybe moved to [this place](https://docs.zeebe.io/getting-started/create-a-workflow.html)?

**Comment by npepinpe** [comment]
It was merged with the normal BPMN documentation, e.g.: https://docs.zeebe.io/bpmn-workflows/service-tasks/service-tasks.html (see Additional Resources at the bottom)

If you guys would like to contribute to a modeler specific section feel free to open a PR (or if it's not clear how to get started adding docs to Zeebe just visit us or interrupt one of us and we can get that going)

**Comment by pinussilvestrus** [comment]
@npepinpe we had a link inside the Zeebe Modeler to refer to this documentation:

![image](https://user-images.githubusercontent.com/9433996/68570205-610f8500-0460-11ea-814f-1b395a499f04.png)

**Proposal**: Link to the [workflow documentation](https://docs.zeebe.io/getting-started/create-a-workflow.html). What would be nice there is a reference on how to download the Modeler.

**Comment by saig0** [comment]
Instead of a link to the Zeebe getting-started, you could link from the Modeler to the Zeebe BPMN overview page: https://docs.zeebe.io/bpmn-workflows/bpmn-primer.html. It also contains a link to download the modeler :)

**Comment by jwulf** [comment]
Deep links are fragile....---- On Mon, 11 Nov 2019 17:56:53 +1000  Niklas Kiefer<notifications@github.com> wrote ----@npepinpe we had a link inside the Zeebe Modeler to refer to this documentation: 
 
Proposal: Link to the workflow documentation. What would be nice there is a reference on how to download the Modeler.

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/141.
