### ISSUE TITLE
Notarize Zeebe Modeler

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#148]
__What should we do?__

On the Camunda Modeler side, we introduced notarization, cf. https://github.com/camunda/camunda-modeler/pull/1585. This stuff will be included when we pull in the `camunda-modeler@3.5` changes.

@barmac what else needs to be done to achieve overall Catalina support?

__Why should we do it?__

We need support for macOS Catalina.

---

Related to https://github.com/zeebe-io/zeebe-modeler/issues/149
Related to https://github.com/zeebe-io/zeebe-modeler/issues/160

**Comment by barmac** [comment]
Besides applying the changes from camunda/camunda-modeler#1585, Apple credentials will have to be added. Cf. https://github.com/camunda/camunda-modeler/blob/c47c8381fe1911f17fab8792ca614ac4d190bb53/tasks/after-sign/notarize.js#L51

**Comment by pinussilvestrus** [comment]
After we hooked the camunda-modeler@3.6 changes into, we would be able to fix that one, too @barmac

**Comment by pinussilvestrus** [comment]
Due to the pending notarization, the mac nightly build is broken: https://travis-ci.com/zeebe-io/zeebe-modeler/jobs/283292231?utm_medium=notification&utm_source=email

**Comment by barmac** [comment]
I am on it.

**Comment by barmac** [comment]
Current nightly is already notarized and future releases will be, too.

**Comment by pinussilvestrus** [comment]
👍
