### ISSUE TITLE
MacOS Modeler App cannot be opened in macOS Catalina

### ISSUE THREAD

**Issue by grexe** [zeebe-io/zeebe-modeler#149]
On MacOS 10.15.1 (19B88), I cannot open latest Mac app 0.8.0 and get an error message that the app cannot be searched for malware and I should get an updated version.

You can disable this warning and override the system protection:
https://support.apple.com/en-us/HT202491

However in the end this is not desirable and safe.
I am not a Mac developer, but is it possible to get the author whitelisted so I can simply check "allow apps from 3rd party developers"?

---

Depends on https://github.com/zeebe-io/zeebe-modeler/issues/148

**Comment by nikku** [comment]
Is this related to notarization? https://github.com/zeebe-io/zeebe-modeler/issues/148

**Comment by nikku** [comment]
For future bug reports, could you please use our existing bug report template? We may not be able to provide you the necessary feedback otherwise.

**Comment by grexe** [comment]
yep will do, sorry, seemed so cluttered for a simple bug, but you're right @nikku .
Yes indeed it seems to be closely related to #148 - didn't know the correct term used in MacOS land, still new to the Mac (only ran Linux after a brief detour to a Powerbook G4;)

**Comment by barmac** [comment]
This will be fixed in the next release.

Closed via https://github.com/zeebe-io/zeebe-modeler/issues/148
