### ISSUE TITLE
Can not set a correlation key of a message event subprocess 

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-modeler#151]
__Describe the Bug__

When I model an event subprocess with a message start event then I can not set the correlation key of the message. The correlation key is required to execute the workflow. 

Current workaround: create the message via message boundary event or intermediate catch event and use it for the event subprocess.

__Steps to Reproduce__

![zeebe-modeler-message-event-subprocess](https://user-images.githubusercontent.com/4305769/70894541-7f334c80-1fed-11ea-9881-115643684893.gif)

__Expected Behavior__

I can set the correlation key of the message inside the event subprocess. 

Similar to an intermediate message catch event or a message boundary event. Note that a message start event on process level does not have a correlation key.

__Environment__

- OS: Ubuntu
- Zeebe Modeler Version: 0.8.0

**Comment by nikku** [comment]
Thanks for your feedback. We scheduled this as a bug fix for our next Zeebe Modeler release.

**Comment by oguzeroglu** [comment]
Closed via #154.
