### ISSUE TITLE
Timer event definition of event subprocess is not consistent with boundary event

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-modeler#156]
__Describe the Bug__

The options for the timer event definition of an event subprocess are not consistent with the options for a boundary event.

// | event subprocess | boundary event
-- | ----------------------- | ---------------------
interrupting | date, cycle | duration
non-interrupting | date, cycle | duration, cycle

__Steps to Reproduce__

1. creating a new BPMN
2. Adding an event subprocess
3. Adding a timer start event to the event subprocess
4. Open the properties panel to configure the timer event definition

__Expected Behavior__

The timer start event of the event subprocess have the same options as the boundary event to configure the timer event definition.

__Environment__

- OS: Ubuntu
- Zeebe Modeler Version: 0.8.0

**Comment by oguzeroglu** [comment]
@saig0 Thanks for the report! I made a fix, before I open a PR could you verify this is the correct behavior:

| Timer Start Event (not inside event sub process) | Timer Boundary Event (interrupting) | Timer Boundary Event (non-interrupting) | Timer Start Event - (interrupting / inside Event Subprocess) | Timer Start Event (non-interrupting / inside Event Subprocess) |
|--------------------------------------------------|-------------------------------------|-----------------------------------------|--------------------------------------------------------------|----------------------------------------------------------------|
| Date, cycle                                      | Duration                            | Duration, cycle                         | Duration                                                     | Duration, cycle                                                |
|                                                  |                                     |                                         |                                                              |                                                                |
|                                                  |                                     |                                         |                                                              |                                                                |

**Comment by saig0** [comment]
Looks good :+1:

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/commit/34dae2ce0d27a0be96635ed559c2b3f0ccdf7281
