### ISSUE TITLE
I can model an error end event

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-modeler#162]
__Is your feature request related to a problem? Please describe.__

I want to add an error end event to my workflow. The error may be caught inside this workflow or by a parent workflow.

__Describe the solution you'd like__

I can add an error end event to my workflow. The end event should reference an error with an `errorCode`. Same behavior as for an error start or boundary event. 

__Describe alternatives you've considered__

No.

__Additional context__

Error end events will be supported in Zeebe version 0.23.0.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/commit/5fa38327b525cd4b79b900927002e5f4661cee97
