### ISSUE TITLE
link to the documentation is broken

### ISSUE THREAD

**Issue by grexe** [zeebe-io/zeebe-modeler#168]
__Describe the Bug__

Selecting Help->Documentation tries to open `https://docs.zeebe.io/bpmn-modeler/README.html` which is broken. 
I could not find any documentation dedicated solely to Zeebe Modeler, it is rather distributed across the common Zeebe documentation.

__Steps to Reproduce__

in the Modeler, select the menu Help->Documentation

__Expected Behavior__

Default browser should open with help landing page.

__Environment__

- OS: MacOS 10.15.3 (19D76)
- Zeebe Modeler Version: 0.8.0

**Comment by pinussilvestrus** [comment]
Seems like https://github.com/zeebe-io/zeebe-modeler/pull/141 got missed in the last release.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/commit/28378cb629f4a53e0456f0c22b5f0378d51e6cbf

**Comment by pinussilvestrus** [comment]
Thanks for sharing, @grexe !
