### ISSUE TITLE
provide a navigable diagram overview pane

### ISSUE THREAD

**Issue by grexe** [zeebe-io/zeebe-modeler#171]
__Is your feature request related to a problem? Please describe.__

With bigger diagrams, it's very easy to get lost. I need a better way to navigate inside my diagrams. Currently, I always have to zoom out, find out where I am, where I want to go, and zoom into the target space.

__Describe the solution you'd like__

Usually, graphical editors provide a navigable overview in some corner (e.g. below the property pane, there would be enough space).
Additionally, quick search for names and IDs would be useful.

__Describe alternatives you've considered__

3D and VR solutions;=)

**Comment by pinussilvestrus** [comment]
> Usually, graphical editors provide a navigable overview in some corner (e.g. below the property pane, there would be enough space)

What about the minimap?

![image](https://user-images.githubusercontent.com/9433996/73743816-b9001400-474f-11ea-9efb-cb13f5f8a727.png)

Doesn't it do exactly what you described?

> Additionally, quick search for names and IDs would be useful

`CTRL/CMD + F` opens a search bar

![image](https://user-images.githubusercontent.com/9433996/73743906-e8af1c00-474f-11ea-8974-0c78d7ed0384.png)

**Comment by pinussilvestrus** [comment]
Is anything besides that you can think of to help in navigation purposes?

**Comment by grexe** [comment]
oh no I'm sorry, could have sworn I've checked that, but you're right - both perfectly fit the requirements of this RFE, so feel free to close and thanks for pointing out the solutions!

**Comment by pinussilvestrus** [comment]
🎉
