### ISSUE TITLE
Empty page does not have correct styles

### ISSUE THREAD

**Issue by oguzeroglu** [zeebe-io/zeebe-modeler#178]
The empty page does not seem to be affected by new button styles:

![Screenshot 2020-02-20 at 15 48 52](https://user-images.githubusercontent.com/15003836/74945853-b3195c80-53f8-11ea-9e23-7e7eefcd2245.png)

It should be like this (screenshot from Camunda Modeler):
<img width="1103" alt="Screenshot 2020-02-20 at 15 50 36" src="https://user-images.githubusercontent.com/15003836/74945886-c4626900-53f8-11ea-9d3a-7ded6db2bee9.png">

**Comment by pinussilvestrus** [comment]
Closed via bf2bbd529f61b83f75a42e19aa9d689e5d7ae404
