### ISSUE TITLE
Nightly Crashes on Startup

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#179]
__Describe the Bug__

While starting the current nightly build, the app got crashed immediately:

![image](https://user-images.githubusercontent.com/9433996/75016783-0983ab00-548c-11ea-9a53-fc2ee9377a9f.png)

__Steps to Reproduce__

1. Download [nightly](https://zeebe-modeler-nightly.s3.eu-central-1.amazonaws.com/zeebe-modeler-nightly-mac.dmg) version
2. Start the downloaded Zeebe Modeler

__Expected Behavior__

Everything works well without crashing

__Environment__

- OS: macOS 10.15.2
- Zeebe Modeler Version: `nightly`

**Comment by oguzeroglu** [comment]
Closed via #180
