### ISSUE TITLE
I can add a payload mapping to a sequence flow

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zeebe-modeler#19]
For sequence flows leading to a parallel gateway, users can define a payload mapping. The purpose is to merge the payloads of the branches into one in a predictable fashion. This mapping is an extension elemement of the sequence flow.

Example:

```
<sequenceFlow id="flow" sourceRef="task" targetRef="join">
  <extensionElements>
    <zeebe:payloadMappings>
      <zeebe:mapping source="$.key1" target="$.mappedKey1" type="PUT"/>
      <zeebe:mapping source="$.key2" target="$.mappedKey2" type="COLLECT"/>
    </zeebe:payloadMappings>
  </extensionElements>
</sequenceFlow>
```

`source` and `target` can contain any String. `type` is an enum with values `PUT` and `COLLECT`. `PUT` should be the default.

**Comment by dominikhrn** [comment]
Done with release 0.2.0
