### ISSUE TITLE
Handle Endpoint Configuration the same way as in Camunda Modeler

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#190]
__Is your feature request related to a problem? Please describe.__

In _every_ tab, we use the same stored endpoint configuration. Note in the following screencast how the same configuration is filled into the modal, no matter what file we have opened.

![Kapture 2020-04-02 at 11 02 20](https://user-images.githubusercontent.com/9433996/78230377-882f2780-74d1-11ea-9d0c-097bd19d91c7.gif)

We store a single endpoint configuration currently:

```json
 "DEPLOYMENT_CONFIG": {
    "audience": "",
    "camundaCloudClientId": "dump",
    "camundaCloudClientSecret": "dump",
    "camundaCloudClusterId": "dump",
    "connectionMethod": "camundaCloud",
    "deploymentName": "simple",
    "oauthClientId": "",
    "oauthClientSecret": "",
    "oauthURL": "",
    "rememberCredentials": true,
    "zeebeContactPointOauth": "",
    "zeebeContactpointSelfHosted": "0.0.0.0:26500"
 }
```

This does not match with the behavior we have in the Camunda Modeler, where we

* Diagram specification (deployment name) is saved per file
* Endpoint configuration is saved globally and referenced per file

__Describe the solution you'd like__

Align endpoint configuration persistence behavior with Camunda Modeler (details above).

__Additional Context__

Example Config how we have in the Camunda Modeler:

```json
{
  // ...
  "camundaEngineEndpoints": [
    {
      "authType": "bearer",
      "id": "0u3yvpk",
      "rememberCredentials": true,
      "token": "test",
      "url": "http://localhost:8080/rest"
    }
  ],
  "files": {
    "~/BPMN files/diagram_1.bpmn": {
      "deployment-tool": {
        "deployment": {
          "name": "diagram_1"
        },
        "endpointId": "0u3yvpk"
      }
    }
  }
}
```

**Comment by pinussilvestrus** [comment]
Okay, removing the local `config.json` resolved it 🤦🏻‍♂️ Anyway, I'll add a test case to verify it's working at all.

**Comment by pinussilvestrus** [comment]
@oguzeroglu I was able to reproduce it again. Seems like we're not saving the configuration for each file. This is a part of the `config.json`

```json
 "DEPLOYMENT_CONFIG": {
    "audience": "",
    "camundaCloudClientId": "DCLBoZVGwNiVmrZBb4ELTrMR1AJtvlBx",
    "camundaCloudClientSecret": "bQE9RDrmUvKKhoCHc7LMenE5WIjvbrE6IIwVdNEkpwywOk3HRKtXS7W65jVxxNWf",
    "camundaCloudClusterId": "d5fd3b34-f3b0-4faa-8e2f-ff57b9358a2b",
    "connectionMethod": "camundaCloud",
    "deploymentName": "complex",
    "oauthClientId": "",
    "oauthClientSecret": "",
    "oauthURL": "",
    "rememberCredentials": true,
    "zeebeContactPointOauth": "",
    "zeebeContactpointSelfHosted": "0.0.0.0:26500"
  }
```

And therefore this config is used for any tab. Is this intended? In Camunda Modeler we save deployment details for any file separately:

```json
"files": {
    "/Users/niklas.kiefer/Documents/BPMN files/diagram_1.bpmn": {
      "deployment-tool": {
        "deployment": {
          "name": "diagram_1"
        },
        "endpointId": "0u3yvpk"
      },
}
```

But saving endpoints in a different place so we might be able to have configurable, multiple endpoints in the future.

**Comment by barmac** [comment]
I would expect the last saved endpoint to be a default for a new diagram, but the deployment name should always be set per file only. Also, if I use a different endpoint configurations for different files, the editor should not mix them up.

**Comment by nikku** [comment]
We should align this with the Camunda Modeler behavior.

**Comment by pinussilvestrus** [comment]
I updated the description to match what we discussed.

**Comment by barmac** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/197
