### ISSUE TITLE
Limit differences after BPMN save

### ISSUE THREAD

**Issue by ajeans** [zeebe-io/zeebe-modeler#191]
__Is your feature request related to a problem? Please describe.__

We work with a lot of BPMNs and are using GitOps to manage and deploy them.
* It is very important to us that a BPMN file doesn't change unless it really has been changed in the modelet
* It is very important to us that the diff is minimal after a change
This gives us a nice property of GitOps: the bpmns are diffable and the make some sense to a human being. 

Looking at some git diffs after minor edits, it seems that some elements in the BPMN files are not sorted with clear rules. 

As a test, moving a task element a bit to the left in the modeler and saving the BPMN will yield more changes than necessary:
* some pixel value changes in `<dc:Bounds>` <= this is expected
* a service task is reorded and moves up or down in the file <= my problem

__Describe the solution you'd like__
Elements in the BPMN file should be sorted by name under their parent.

__Describe alternatives you've considered__

Any sorting would do, I want the order to be stable across saves.

__Additional context__
Will attach a diff after a save with modeler 0.8.0

**Comment by ajeans** [comment]
DIFF saved as TXT (apparently, github doesn't like diff files)
[bpmn.diff.txt](https://github.com/zeebe-io/zeebe-modeler/files/4407744/bpmn.diff.txt)

**Comment by nikku** [comment]
Elements are sorted with regards to their visual priority. That means: If you move an element, it will be put on top of all other elements in the same scope (some exceptions apply).

The visual effect is what I would expect as a user:

![capture lHTXvW_optimized](https://user-images.githubusercontent.com/58601/78286335-27c7d680-7521-11ea-8d7a-6fe0903674d0.gif)

Is there any other occasion where you see that unwanted noise? Unfortunately we'll not be able to address that particular instance.

**Comment by nikku** [comment]
There do exist visual diff tools that may better support gitops for BPMN files: https://github.com/38leinaD/bpmn-diff.

**Comment by ajeans** [comment]
Thanks @nikku , I have installed bpmn-diff and it is indeed a useful tool for GitOps.

I created a github repository with a very simple bpmn (start -> activity -> end) at https://github.com/ajeans/bpmn-diff-test/commits/master
* Commit 1 is the creation of the BPMN
* Commit 2 moves the activity and the diff is as expected: https://github.com/ajeans/bpmn-diff-test/commit/a9a875bf43414bee19112502de226dfc495d5cf0
* Commit 3 adds a lane under all elements
* Commit 4 moves the activity again, and we see the extra churn: https://github.com/ajeans/bpmn-diff-test/commit/8c94cf5b70a6d93c9150b260c7a43b925826eb09

With your explanation, I understand that adding pools & lanes are the reason where the churn comes from. That's a pity though...
