### ISSUE TITLE
Nightly builds are crashing

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#192]
__Describe the Bug__

The Zeebe Modeler Nightly Builds are not running through currently, cf. https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/311138115#L491

__Steps to Reproduce__

Simply go to the [build](https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/311138115#L491) and see the nightly builds are crashing.

__Expected Behavior__

It should run through.

__Additional Context__

* [Travis configuration](https://github.com/zeebe-io/zeebe-modeler/blob/develop/.travis.yml)

**Comment by nikku** [comment]
Any progress on this one?

**Comment by nikku** [comment]
If not, maybe it makes sense to hand it over to, i.e. @barmac?

**Comment by barmac** [comment]
This might be related: https://github.com/electron-userland/electron-builder/issues/3629

**Comment by barmac** [comment]
I just noticed that in [the last successful build](https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/309559569) we used winCodeSign 2.5.0 while the current build fails on winCodeSign 2.6.0
