### ISSUE TITLE
Add support for exclusive Gateway and Conditions

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe-modeler#2]
The new release will feature the exclusive Gateway and Conditions.
We should add support in the modeler.

**Comment by dominikhrn** [comment]
done like described on that [https://docs.zeebe.io/bpmn-workflows/gateways.html](page)

**Comment by dominikhrn** [comment]
Commit Message is a bit confusing... Should be Exclusive Gateway not Event... Sorry ;)

**Comment by saig0** [comment]
@dominikhrn , it seems that it's currently not possible to set the default flow of the gateway.  

Btw, could you change "Expression" to "Condition expression" to make it more clear.

**Comment by dominikhrn** [comment]
Just download it again.

**Comment by saig0** [comment]
Perfect. Thank you!
