### ISSUE TITLE
Task types are not intuitively discoverable by users

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-modeler#204]
Users are struggling to find the task types in 0.8.

See here: https://forum.zeebe.io/t/modeler-not-functioning-on-windows-10/870/13

Suggestion:

Make all tasks service task by default. This is the 80% use case of new users and removes initial friction in the zero-to-hero path.

**Comment by phileas74** [comment]
Another option would be to show all possible types already when selecting a base task from the pallette. For instance, selecting "Intermediate/Boundary Event" from the pallette would open the same pop-up menu as you get when selecting the wrench icon on a node in the diagram.

**Comment by nikku** [comment]
> Another option would be to show all possible types already when selecting a base task from the pallette. For instance, selecting "Intermediate/Boundary Event" from the pallette would open the same pop-up menu as you get when selecting the wrench icon on a node in the diagram.

This is available as a hiddenf feature when creating an element via `CTRL/CMD + drop` already.

**Comment by nikku** [comment]
Right now making service tasks the default (this is where we came from) is a suitable solution.

Looking into the future, as Zeebe will get more features, this won't be the appropriate solution anymore.

A few things we can leverage

* linting
* improved getting started / documentation / hands on guides
* changes in the editor behavior

Thanks for your feedback guys. We're considering different options and _zero to hero_ aka smooth getting started is an important aspect of the tooling, of course.

**Comment by nikku** [comment]
Places where the documentation does not match the current Modeler behavior:

* https://docs.zeebe.io/getting-started/create-a-workflow.html
* https://docs.zeebe.io/bpmn-workflows/timer-events/timer-events.html `> Using the BPMN modeler`

**Comment by nikku** [comment]
We will update the documentation accordingly to feature the wrench too.

**Comment by pinussilvestrus** [comment]
[This part](https://docs.zeebe.io/bpmn-workflows/bpmn-primer.html#modeling-bpmn-diagrams) would also have to be updated right? (screencast)

**Comment by nikku** [comment]
Yes.

**Comment by pinussilvestrus** [comment]
Made the updates in https://github.com/zeebe-io/zeebe/pull/4325

**Comment by nikku** [comment]
:clap:

**Comment by nikku** [comment]
Closing this as https://github.com/zeebe-io/zeebe/pull/4325 is going to be merged at some point.

Good work @pinussilvestrus :clap:
