### ISSUE TITLE
Improve CI performance

### ISSUE THREAD

**Issue by barmac** [zeebe-io/zeebe-modeler#210]
* [ ] Group same-stage jobs
* [ ] Replace AppVeyor with Travis Windows

---
Looking into the future we could consider moving all distro jobs to the `distro` stage, too: https://docs.travis-ci.com/user/build-stages#naming-your-jobs-within-build-stages

This would speed up the build significantly.

Right now we build each distribution one after the other.

If all jobs run within the same stage, they run in paralle.

_Originally posted by @nikku in https://github.com/zeebe-io/zeebe-modeler/pull/207#issuecomment-614194410_

**Comment by nikku** [comment]
Did not implement the AppVeyor replacement. Open for future investigation :beers:
