### ISSUE TITLE
Be able to see zeebe-client-node-js logs in dev console

### ISSUE THREAD

**Issue by oguzeroglu** [zeebe-io/zeebe-modeler#217]
__Is your feature request related to a problem? Please describe.__

Related to: #216 

In order to help our users in case of errors, we want to be able to see the full logs of zeebe-client-node-js library. This should also let us consult the cloud team to get opinions from them. 

__Describe the solution you'd like__

Pipe the zeebe-client-node-js to frontend and dump to console.

__Describe alternatives you've considered__

Have them written to a .log file using the nodejs filesystem functionality from the backend. Do circular logs because we don't want to cause memory issues.

**Comment by nikku** [comment]
I guess we can close this one?

We have that information in the app logs and users are able to share them.

**Comment by oguzeroglu** [comment]
Fixed via #222
