### ISSUE TITLE
Editor doesn't allow blanks

### ISSUE THREAD

**Issue by SHOZ2020** [zeebe-io/zeebe-modeler#223]
__Describe the Bug__

Can't enter FEEL expressions in the input parameters of a service task.

Get the error "Source must not contain spaces".

__Steps to Reproduce__

1. Create a service task
2. go to the input/output parametrers task
3. Create a new input parameter (click the +)
4. Enter "=if (variable = null) then 1 else variable + 1"
5. Error message appears - "source must not contain spaces"

__Expected Behavior__

Editor should accept valid FEEL expressions

__Environment__

- OS: Ubuntu 18.04.3
- Zeebe Modeler Version: 0.9.0

**Comment by saig0** [comment]
This restriction is also enabled for other attributes that allow FEEL expressions:
* service task type
* source attribute of input and output parameters (i.e. variable mappings)

Current overview of the attributes that can be expressions: https://docs.zeebe.io/reference/expressions.html

**Comment by nikku** [comment]
Seems like we need to [update our validation to support FEEL](https://github.com/zeebe-io/zeebe-modeler/search?q=%22not+contain+spaces%22&unscoped_q=%22not+contain+spaces%22).

**Comment by pinussilvestrus** [comment]
We decided to have a quick fix for this issue in the next release and move the advanced FEEL validation to another issue, cf. https://github.com/zeebe-io/zeebe-modeler/issues/238.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/240
