### ISSUE TITLE
Use last endpoint details as default

### ISSUE THREAD

**Issue by barmac** [zeebe-io/zeebe-modeler#227]
__Is your feature request related to a problem? Please describe.__

I like it that I don't have to specify details again and again in Camunda Modeler. I would like to have it in Zeebe Modeler too. Currently, the feature is missing 🐵 .

__Describe the solution you'd like__

Use last endpoint as the default.

__Describe alternatives you've considered__

None.

__Additional context__

We have it in Camunda Modeler.

**Comment by MaxTru** [comment]
I assume this would also store Cluster ID, Client ID, Client Secret
