### ISSUE TITLE
Migrate to Node Zeebe client 0.23.0

### ISSUE THREAD

**Issue by oguzeroglu** [zeebe-io/zeebe-modeler#230]
We should migrate to [Node Zeebe Client 0.23.0](https://github.com/creditsenseau/zeebe-client-node-js/releases/tag/v0.23.0) which contains a JS only implementation for gRPC operations. That'd help us limit the size of Zeebe Modeler build and also build time would be much faster.

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/issues/233.
