### ISSUE TITLE
Consistently refuse non QName process ids.

### ISSUE THREAD

**Issue by ajeans** [zeebe-io/zeebe-modeler#237]
__Describe the Bug__

In the modeler, when assigning an "Id" in the "General" tab, QName compliance is enforced.
If I try to input "2fa-sms", I get an error msg "Id must be a valid QName"

![image](https://user-images.githubusercontent.com/2376384/88898797-8beb7480-d24d-11ea-8107-aa8a51236855.png)

However, when I create a "Call Activity" element in a BPMN, I can assign a non QName value in tab "General" > "Details" >  "Process Id"  

![image](https://user-images.githubusercontent.com/2376384/88899057-e684d080-d24d-11ea-9bd3-555bb4e0c1dd.png)

AFAIU, the process-id in the call activity must match the BPMN general id, so there seems to be a consistency problem here.

__Steps to Reproduce__

1. Create a new BPMN
2. Add a call activity to it, with process-id "123" 
3. Save the BPMN
4. Create a second BPMN
5. Define its id as "123" 

__Expected Behavior__

If QName is indeed mandatory for process-ids, it should also be enforced in the details of the call activity. 

__Environment__

- OS: Ubuntu 20.04
- Zeebe Modeler Version: 0.9.1

**Comment by philippfromme** [comment]
Good point. Thanks for reporting!

**Comment by MaxTru** [comment]
Will be fixed upstream tracked via [bpmn-js-properties-panel/issues/346](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/346).

**Comment by MaxTru** [comment]
* There is a validation already implemented (https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/Utils.js#L169) and I would assume it can be re-used
* This validation is already used for the Id field (https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/bpmn/parts/IdProps.js#L35)
* To resolve this issue, we would also need to add that validation in zeebe modeler (https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/app/tabs/bpmn/custom/properties-provider/parts/CallActivityProps.js)

**Comment by adithyaakrishna** [comment]
@MaxTru Can I work on this issue?
