### ISSUE TITLE
I can define output variable mappings on all events

### ISSUE THREAD

**Issue by saig0** [zeebe-io/zeebe-modeler#242]
__Is your feature request related to a problem? Please describe.__

Currently, I can define output variable mappings only for message start/intermediate/boundary events. For some use cases, it would be useful to define the mappings also for other types of events. For example:
* none start event: initialize variables that are used later in the workflow
* none end event: collect/aggregate variables that are sent back as response of the create instance command 

Zeebe is supporting output mappings for all events already.

__Describe the solution you'd like__

I can define output variable mappings on all kinds of start, intermediate, boundary, and end events.

__Describe alternatives you've considered__

If I can not define the output mappings in the workflow then the transformation/creation of the variables needs to be done in job worker or application.

__Additional context__

**Comment by MaxTru** [comment]
I assume _"Intermediate events"_ includes `IntermediateCatchEvent` and *IntermediateThrowEvent`

**Comment by saig0** [comment]
Super fast. Awesome :tada:
