### ISSUE TITLE
I would Like to Translate the Code of conduct in Hindi (हिंदी) for Indian users.

### ISSUE THREAD

**Issue by DebugAgrawal** [zeebe-io/zeebe-modeler#262]
__What should we do?__

Translate the code of conduct  and also other general docs in other native languages 

__Why should we do it?__

This helps developers from different communities and countries or region to understand the purpose of this project in more better way.

**Comment by nikku** [comment]
Please do not do this. As non-speakers of the language we will be unable to review and value your contribution accordingly. 

I am not an English native myself, however, as we develop collaboratively we should settle down on one language that we can learn and use. 

Our language of communication is English and the code of conduct reflects that.

**Comment by nikku** [comment]
Any thoughts @zeebe-io/modeling?

**Comment by barmac** [comment]
For the reason of being unable to verify the content, I agree with @nikku that there should be only one official language version of the Code of Conduct.

**Comment by philippfromme** [comment]
We're not going to do this. Why should we have our code of conduct in English and Hindi but not, say, German or Spanish?

**Comment by DebugAgrawal** [comment]
> Please do not do this. As non-speakers of the language we will be unable to review and value your contribution accordingly.
> 
> I am not an English native myself, however, as we develop collaboratively we should settle down on one language that we can learn and use.
> 
> Our language of communication is English and the code of conduct reflects that.

Totally agree with it.👍

**Comment by DebugAgrawal** [comment]
> We're not going to do this. Why should we have our code of conduct in English and Hindi but not, say, German or Spanish?

Yes sure. 👍
