### ISSUE TITLE
Implement toggle switch for propageteAllChildVariables setting 

### ISSUE THREAD

**Issue by MaxTru** [zeebe-io/zeebe-modeler#267]
__Is your feature request related to a problem? Please describe.__

Implement toggle switch for propageteAllChildVariables setting propagateAllChildVariables and disabling/deleting output parameter mappings. 

__Describe the solution you'd like__

* For the CallActivity I/O tab, a toggle/slider `Propagate all child variables?` will be added on top of the output parameter mapping. This toggle will control whether it is possible to have output parameter mappings or not.
  * Toggle on equals to `true`, and off equals to `false`
  * If the toggle is `on`, it is not possible to add output parameter mappings. 
  * If the toggle is set to `on`, existing output parameter mappings will be deleted.
  * If the toggle is `off`, the output parameter mapping component will work as usual.
* [For new CallActivities created]: the toggle is `off` as default.

__Implementation approach__

- [ ] Create a new behavior which will add the `propgateAllChildVariables` property when creating a new CallActivity
- [ ] Add toggle switch to the Output Parameters and update them based on toggle switch

(Migration I will deal with in a separate issue, see #252)

__Describe alternatives you've considered__

See #252 

__Additional context__

Child of #252

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/271
