### ISSUE TITLE
`X` in Input wrongly formatted

### ISSUE THREAD

**Issue by MaxTru** [zeebe-io/zeebe-modeler#268]
__Describe the Bug__

`X` Button to delete user input for condition is wrongly formatted. See gif
![Peek 2020-10-30 20-38](https://user-images.githubusercontent.com/42800119/97749774-ed8ed980-1aef-11eb-85b4-4498dd1b53c3.gif)

The HTML here is:
```html
<div class="bpp-field-wrapper">
  <input id="zeebe-condition" type="text" name="condition" class="">
     <button class="clear" data-action="clear" data-show="canClear">
       <span>X</span>
     </button>
</div>
```

Seems to be an css issue introduced with migration to bpmn-js-properties-panel@0.37.x

__Steps to Reproduce__

1. Checkout develop branch with commit https://github.com/zeebe-io/zeebe-modeler/commit/68e0e786ff501c1724b57b289103387a6f1dc926 or later
2. run `npm dev`
3. Edit the condition expression field on a sequence flow

__Expected Behavior__
Correct format

__Environment__

- OS: Arch Linux
- Zeebe Modeler Version: Commit https://github.com/zeebe-io/zeebe-modeler/commit/68e0e786ff501c1724b57b289103387a6f1dc926

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/issues/273.
