### ISSUE TITLE
Builds, starts, does not operate on Ubuntu 18.10

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-modeler#27]
I can build the app on Ubuntu 18.10, and run it. I get an electron app up. The `Help` Menu items work, but the `File` menu items dispatch clicks and behave as expected for menu items, but produce no side-effects.

Running from a terminal, I see "Window focused" messages, but nothing when clicking `File` menu items - aside from `File > Quit`, which produces `Initiating termination of the application`, but does not quit the application. I have to process kill it to bring it down.

**Comment by dominikhrn** [comment]
Hi @jwulf,

Thanks for reporting this issue! I will check that.
But why are you using the sources and npm to start the modeler in developing mode?
You could download the latest release [here](url
https://github.com/zeebe-io/zeebe-modeler/releases/tag/0.4.0)
The problem will not occur that way.

**Comment by jwulf** [comment]
Thanks, that works.
