### ISSUE TITLE
Process ID of a Pool can not be seen/edited

### ISSUE THREAD

**Issue by falko** [zeebe-io/zeebe-modeler#278]
__Describe the Bug__

The id of a process inside a pool can be neither seen nor edited in the properties panel. This might be a blocker for users because without the process id they can not start process instances. The only workaround is working with the XML, in which searching is uncomfortable and editing is error-prone.

__Steps to Reproduce__

1. Create a new BPMN model
2. Create a pool by dragging it from the palette onto the canvas
3. The process id can no longer be seen/edited. Selecting the pool shows only the properties of the participant visualized by the pool. Selecting the canvas shows only the properties of the collaboration.

![image](https://user-images.githubusercontent.com/40038/100939811-3c68ce00-34f7-11eb-8e4b-84f64af48de4.png)

__Expected Behavior__

There is always a way to edit the process id.

In Camunda Modeler, selecting the pool also shows the properties of its process, which might also not be the best UX approach.

![image](https://user-images.githubusercontent.com/40038/100940169-c3b64180-34f7-11eb-999f-bc55688a454f.png)

__Environment__

- OS: Ubuntu 20.04.1 LTS
- Zeebe Modeler Version: 0.10.0

**Comment by MaxTru** [comment]
Thanks for reporting. I can reproduce it. This indeed can be a blocker.

**Comment by andreasgeier** [comment]
This issue is related: https://github.com/camunda/camunda-modeler/issues/1738

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/issues/284.
