### ISSUE TITLE
Revert File

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-modeler#281]
__Is your feature request related to a problem? Please describe.__

I edit a file, then I want to discard the edits. There is no "Revert File" in the File menu. I also cannot revert by re-opening the file. I have to close the file, Don't Save, then open it again.

__Describe the solution you'd like__

A "Revert File" command in the File menu.

**Comment by nikku** [comment]
I have some questions to better understand your case:

* Why would you like to revert in the first place?
* What about version control (revert is built in there)?
* You know other editors have similar functionality you can point us to?

**Comment by nikku** [comment]
Closing this issue, as we miss the follow up.

I'm assuming that any kind of source control to be able to _revert_ is a better place solution for reverting.
