### ISSUE TITLE
Support UserTasks (WIP)

### ISSUE THREAD

**Issue by MaxTru** [zeebe-io/zeebe-modeler#283]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

As soon as Zeebe engine supports UserTasks, the Zeebe Modeler shall support them as well.

This issue will be detailed, once the respective decisions for Zeebe Engine were made.

**Comment by pinussilvestrus** [comment]
We should consider bringing this directly into https://github.com/camunda/camunda-bpmn-js, to avoid later migrations.

**Comment by menski** [comment]
See the final proposal of the Zeebe user task form support:
https://github.com/zeebe-io/zeebe/issues/6116#issuecomment-780424321

**Comment by MaxTru** [comment]
Will be tracked via https://github.com/camunda/camunda-modeler/issues/2104
