### ISSUE TITLE
Update deployment target names

### ISSUE THREAD

**Issue by andreasgeier** [zeebe-io/zeebe-modeler#292]
__Is your feature request related to a problem? Please describe.__

The names of the endpoint targets in the Zeebe deployment dialog are outdated.

![Screen Shot 2021-03-05 at 15 39 30](https://user-images.githubusercontent.com/938244/110130238-15a58680-7dc9-11eb-9323-6bd72d8d0809.png)

__Describe the solution you'd like__

According to @felix-mueller we should call it "Camunda Cloud Self-Managed" and "Camunda Cloud SaaS". Please update.

__Describe alternatives you've considered__

Keep it as is.

**Comment by pinussilvestrus** [comment]
Should we really update it here? We recently brought those plugins to the Camunda Modeler ...

**Comment by pinussilvestrus** [comment]
Closing this in favor of https://github.com/camunda/camunda-modeler/issues/2141.
