### ISSUE TITLE
Unable to connect to an HTTPS endpoint

### ISSUE THREAD

**Issue by younes-io** [zeebe-io/zeebe-modeler#297]
__Describe the Bug__

I have written and run this snippet as Zeebe Modeler uses `zeebe-node` under the hood:

    const zbc = new ZBClient('0.0.0.0:50051', {
    	oAuth: {
    	  url: 'http://127.0.0.1:4000/token',
    	  audience: '***********************************',
    	  clientId: '***********************************',
    	  clientSecret: '****************************************',
    	  cacheOnDisk: true,
    	},
    	useTLS: true,
    });

Here are the logs:

> 10:52:30.488 | zeebe |  INFO: [topology]: 14 UNAVAILABLE: failed to connect to all addresses
> E0423 10:52:31.487000000 12952 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
> 10:52:31.503 | zeebe |  INFO: [topology]: Attempt 2 (max: -1).
> 10:52:31.505 | zeebe |  INFO: [topology]: 14 UNAVAILABLE: failed to connect to all addresses
> 10:52:32.505 | zeebe |  INFO: [topology]: Attempt 3 (max: -1).
> 10:52:32.507 | zeebe |  INFO: [topology]: 14 UNAVAILABLE: failed to connect to all addresses
> E0423 10:52:33.103000000 12952 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

However, when I do `useTLS: false`, it does work ! I have another endpoint in HTTPS, and it only works when `useTLS` is set to `false`, otherwise, I get the error above!

__Steps to Reproduce__

1. Open Zeebe Modeler, and pick OAuth
2. Enter your OAuth credentials
3. Check Zeebe Modeler logs:
    - Windows: `C:\Users\yourUser\AppData\Roaming\zeebe-modeler\Zeebe Modeler\logs\log.log`
    - MacOS: `~/Library/Logs/Zeebe Modeler/log.log`

__Expected Behavior__

The same behavior as when the authentication method is set to `None`.

__Environment__

- OS: Windows 10 10.0.1904
- Zeebe Modeler Version: 0.12
- Node: 12.18.3
- npm: 6.14.9
- Chrome: 90.0.4430.85

**Comment by MaxTru** [comment]
@younes-io  Thanks for reporting this issue.

I understand from the description that you already located the bug in `zeebe-node` and that even when using `zeebe-node` outside of the CamundaModeler you cannot connect to a TLS endpoint by setting `useTLS` to `true`. Is my understanding correct?

If my understanding is correct, then we should open an issue directly in the `zeebe-node` project.

Thank your for a quick confirmation.

**Comment by younes-io** [comment]
Hello @MaxTru 

Indeed, your understanding is correct. I'm using Zeebe Modeler, not Camunda Modeler, which also uses `zeebe-node` under the hood.

I have reported this issue in the `zeebe-node` project : https://github.com/camunda-community-hub/zeebe-client-node-js/issues/218

Best regards,

**Comment by younes-io** [comment]
Opened an issue here : https://github.com/camunda-community-hub/zeebe-client-node-js/issues/218

**Comment by MaxTru** [comment]
Thank you!
