### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe-modeler#3]
Once there is binary release which users can download, we should start featuring it in the docs.

Places where it makes sense:

* https://docs.zeebe.io/basics/workflows.html#the-modeler
* Getting started guide

**Comment by menski** [comment]
There is a whole section for the modeler https://docs.zeebe.io/bpmn-modeler/README.html. Which should be updated https://github.com/zeebe-io/zeebe/issues/1881 :see_no_evil:. It is also featured in other parts of the https://docs.zeebe.io
