### ISSUE TITLE
I can attach timer/message catch event to activity boundaries

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-modeler#31]
With version 0.4.0, it seems I can't drop a timer/message event directly on the boundary of an activity. It won't allow me dropping it on a task, and on a sub-process it just adds it as a child element.

The workaround is to drop a none event and switch its type, which is OK, but not great UX.

I think it'd be more intuitive to allow dropping the events directly on the boundary of activities.

**Comment by jwulf** [comment]
This workaround is good to know. I've been building them in the Camunda modeler and then opening them in the Zeebe modeler.

**Comment by dominikhrn** [comment]
- [ ] Add CustomBehavior for Boundary Events
- [ ] Adapt modeling rules
- [ ] Testing
- [ ] Refactoring

**Comment by dominikhrn** [comment]
@npepinpe I guess we can remove the IntermediateThrowEvent from the palette? In my opinion we don't need it anymore... The only reason I added that event was for the workaround you described.

**Comment by npepinpe** [comment]
@dominikhrn I agree, it's probably not needed anymore, and won't be for a while.

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/44.
