### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#38]
Updating to the Camunda Modeler @next foundation made us adapt the bpmn.io logo as the application logo. Should this stay the Zeebe Modeler logo or should we use the Zeebe logo instead? @menski

**Comment by menski** [comment]
@nikku I don't have a strong opinion on this matter, so feel free to decide. The only thing which I could imagine is that users who installed the camunda and zeebe modeler could mix them up if both have the same logo. But we can also wait until someone complains.

**Comment by menski** [comment]
Thanks for taking care. I send you an email with the logo, as Github doesn't allow to upload SVGs to an issue. :confused:

**Comment by nikku** [comment]
Will be fixed with general rebranding (coming up some day, maybe).
