### ISSUE TITLE
Zeebe Modeler documented / marketed features

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#39]
Cleaning up the Zeebe Modeler repository I'd be inclined to remove functionality that is undocumented / unused at this stage.

Two things are deletion candidates and I need your input regarding this:

* Element Templates + documentation (is it being used)?
* Plug-ins (is it being used)?

Keep in mind that we may re-add these features any time.

**Comment by dominikhrn** [comment]
Hi @nikku,

I totally agree with the element-templates stuff.
But I am not sure if we should remove the Plug-ins feature.
Thorben wanted to have the token simulation by default -> #12 
We could integrate it as a module, but then activation / deactivation is not possible by default.

**Comment by vasicvuk** [comment]
It would be great to have element templates with documentation in some time since it is very useful feature
