### ISSUE TITLE
Get modeler in sync with camunda-modeler@master

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#48]
As described inside https://github.com/zeebe-io/zeebe-modeler/pull/47 we got the problem now that the commit histories of the `zeebe-modeler` and the base `camunda-modeler` are completely out of sync, caused by a rebase we made inside the master-branch [1]. It can be outlined as follows:

![commithistory](https://user-images.githubusercontent.com/9433996/51590710-3103ef00-1eeb-11e9-8bc4-3ace7dc77bfd.png)

Therefore we have to think about how we resync the histories. The first thing we should try out is to run the synchronization task (`$ npm run sync`), fix all the merge conflicts once and test, whether they come back.

If not so, we will have to think of rebasing the history once again or migrate the history itself, like we did inside #33.

[1]
![image](https://user-images.githubusercontent.com/9433996/51540771-8e4e6080-1e57-11e9-83b2-edde38bc2c6d.png)

**Comment by pinussilvestrus** [comment]
Good news, it seemed to work after executing `npm run sync` and fixing the named 53 conflicts. After doing it a second time, the conflicts don't come back 🎉 I will follow up with a pull request.

**Comment by nikku** [comment]
This will settle down for good, I'm sure :1st_place_medal:.
