### ISSUE TITLE
Add deployment tool

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#53]
Currently, we just disabled the deployment functionality inside the `zeebe-modeler`. Since we made several improvements inside the [`camunda-modeler`](https://github.com/camunda/camunda-modeler/issues/906), it seems to be a good choice to integrate it inside the `zeebe-modeler` too.

__Describe the solution you'd like__

Deploy action in the toolbar is working.

- [ ] Enable deploy action
- [ ] Deploy to Zeebe (cf. [docs](https://stage.docs.zeebe.io/grpc/reference.html#deployworkflow-rpc))

__Describe alternatives you've considered__

...

**Comment by menski** [comment]
I would love to see this feature. But please be aware that Zeebe does not have a Rest API, but we have a node.js client: https://github.com/CreditSenseAU/zeebe-client-node-js#deploy-a-workflow

See also the protocol for reference https://stage.docs.zeebe.io/grpc/reference.html#deployworkflow-rpc

**Comment by oguzeroglu** [comment]
👌
