### ISSUE TITLE
User can set output mappings for message events (start/intermediate/boundary) and receive tasks

### ISSUE THREAD

**Issue by wints** [zeebe-io/zeebe-modeler#58]
@menski I could use some help with detail on this one

**Comment by menski** [comment]
All message events and receive tasks should have a `Input/Output` panel like the service task

**Comment by menski** [comment]
Normally input mappings don't make sense for these elements, but to keep it simple we can just use the same panel as the service task for now

**Comment by dominikhrn** [comment]
@menski I disabled the input mappings for messages 👍

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/62.
