### ISSUE TITLE
Remove output behavior from input/output mappings

### ISSUE THREAD

**Issue by wints** [zeebe-io/zeebe-modeler#59]
Related to: [zeebe-io/zeebe#1878](https://github.com/zeebe-io/zeebe/issues/1878)

@menski to provide more detail if necessary

**Comment by menski** [comment]
In the `Input/Output` tab the `Output Behavior` dropdown has to be deleted
![screenshot-2019-02-21-16 41 01](https://user-images.githubusercontent.com/516296/53181335-a7cdfe00-35f7-11e9-8226-caa438080b02.png)

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/62.
