### ISSUE TITLE
Remove payload mappings for merging parallel gateway sequence flows

### ISSUE THREAD

**Issue by wints** [zeebe-io/zeebe-modeler#60]
Related to: [zeebe-io/zeebe#1629](https://github.com/zeebe-io/zeebe/issues/1629)

@menski to add more detail if necessary

**Comment by menski** [comment]
On sequence flows the `Payload Mappings` tab has to be deleted
![screenshot-2019-02-21-16 37 46](https://user-images.githubusercontent.com/516296/53181127-3ee68600-35f7-11e9-8a52-a9b480a38edd.png)

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/62.
