### ISSUE TITLE
Remove SendTask from pallete and morph menu

### ISSUE THREAD

**Issue by MiguelPires** [zeebe-io/zeebe-modeler#63]
Currently Zeebe doesn't support SendTask so it should be removed from the pallete and morph menu

**Comment by dominikhrn** [comment]
Done 👍

**Comment by MiguelPires** [comment]
Thanks @dominikhrn!

**Comment by nikku** [comment]
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/64.
