### ISSUE TITLE
On creating a new BPMN diagram

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-modeler#68]
__Describe the Bug__

When creating a new BPMN diagram the log opens with a warning about an unresolved reference to `Process_1`. It then fixes the `bpmnElement` reference to the correct id of the `bpmn:process` element.

```
unresolved reference <Process_1>  [warning]
no bpmnElement referenced in <bpmndi:BPMNPlane id="BPMNPlane_1" />  [warning]
correcting missing bpmnElement on <bpmndi:BPMNPlane id="BPMNPlane_1" /> to <bpmn:Process id="Process_19hvxx7" />  [warning]
```

__Steps to Reproduce__

1. Create a new BPMN diagram
2. Look at log

__Expected Behavior__

No warnings are created and the BPMN plane immediately references the correct process id. 

__Environment__

Please complete the following information:

 - OS: Linux
 - Zeeber Modeler Version: 0.6.2

**Comment by nikku** [comment]
Fixed upstream in the latest Camunda Modeler version.
