### ISSUE TITLE
Do not allow to model timer/message start event inside embedded sub process

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-modeler#69]
__Describe the Bug__

At the moment the user is able to model a timer/message start event inside an embedded sub process. This should not be allowed.

__Steps to Reproduce__

1. Model an embedded sub process
2. Add a start event to the sub process
3. Morph it to timer/message start event

__Expected Behavior__

The user should only be allowed to model a none start event inside a embedded sub process.

__Environment__

Please complete the following information:

 - OS: Linux
 - Zeeber Modeler Version: 0.6.2

---

Depends on https://github.com/camunda/camunda-modeler/issues/498

**Comment by nikku** [comment]
Tracked upstream as via https://github.com/camunda/camunda-modeler/issues/498.

**Comment by MaxTru** [comment]
Fixed in https://github.com/bpmn-io/bpmn-js/issues/831
