### ISSUE TITLE
Mid-term vision

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zeebe-modeler#7]
What do you guys think about how we should continue with the "zeebe modeler" mid-term.

I see two general directions in which this could go

* we keep the modeler in a separate repository and maintain it as a fork of the original Camunda modeler
* we have a single Camunda Modeler targeting both Camunda BPM but also Zeebe. The user can then select a "Profile" for the execution platform they are targeting which switches the properties panel and maybe the palette.

I also want to pull in @philippfromme and @nikku for this discussion

**Comment by dominikhrn** [comment]
Think we should also create a zeebe-bpmn-moddle [like that one for camunda](https://github.com/camunda/camunda-bpmn-moddle) 
The [properties provider](https://github.com/zeebe-io/zeebe-modeler/tree/master/client/lib/custom/propertyprovider) should also be placed in the [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/master/lib/provider)

Not sure which option would be the best...
Second one sounds a bit more comfortable (updates, fixes...)

**Comment by nikku** [comment]
We discussed this internally and this is our results:

Short term it probably makes sense to go with the fork to keep the friction between the two projects as low as possible. 

As zeebe matures and becomes a fully functional, awesome part of the Camunda family we would like to support it out of the box in the Camunda Modeler. How to do that in the best way is up for decision :wink:.

**Comment by meyerdan** [comment]
Hi Nico, thank you for the input, that makes a lot of sense.

**Comment by meyerdan** [comment]
I am closing this for the moment
