### ISSUE TITLE
I can morph an intermediate message catch event into a timer event

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-modeler#70]
__Is your feature request related to a problem? Please describe.__

At the moment I can morph an intermediate timer event into a message event but not vice versa.

__Describe the solution you'd like__

I can model an intermediate message catch event and afterwards morph it into an intermediate timer event.

__Describe alternatives you've considered__

Deleting the message event and creating a timer event is a feasible workaround.

__Additional context__

It is already possible to morph an intermediate timer event into a message event, also boundary events can be morphed to the other type.

**Comment by dominikhrn** [comment]
@menski I'll take a look at that this evening. Should be fixed by adding
`'replace-with-timer-intermediate-catch'` to https://github.com/zeebe-io/zeebe-modeler/blob/master/client/src/app/tabs/bpmn/custom/modeler-options/Options.js

**Comment by pinussilvestrus** [comment]
Closed via 57461e2.
