### ISSUE TITLE
Ctrl+Z & Ctrl+Y don't work

### ISSUE THREAD

**Issue by falko** [zeebe-io/zeebe-modeler#72]
__Describe the Bug__

Ctrl+Z & Ctrl+Y don't work. The toolbar buttons do work.

__Steps to Reproduce__

1. Model something
2. Try to und with Ctrl+Z
3. Undo with toolbar button
4. try to redo with Ctrl+Y
5. Redo with toolbar button

__Expected Behavior__

All keyboard shortcuts work as advertised in the menu.

__Environment__

Please complete the following information:

 - OS: Ubuntu 18.04.2 LTS
 - Zeeber Modeler Version: zeebe-modeler-0.6.2-linux-x64

**Comment by nikku** [comment]
Upstream bug https://github.com/camunda/camunda-modeler/issues/1218 got fixed with the latest Camunda Modeler beta release.

**Comment by falko** [comment]
Perfect, thank you!

**Comment by nikku** [comment]
Should be fixed in next nightly.
