### ISSUE TITLE
Pull in Camunda Modeler v3.0.0 upstream

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#74]
Upstream we released the Camunda Modeler `v3.0.0`.

The release fixes two bugs already reported with this app (https://github.com/zeebe-io/zeebe-modeler/issues/68, https://github.com/zeebe-io/zeebe-modeler/issues/72).

__Tasks__

* [ ] Pull in upstream `v3.0.0` changes

**Comment by pinussilvestrus** [comment]
`npm run sync -- -t v3.0.0` would be the appropriate command to execute the sync. I can dot it + fixing appearing conflicts.
