### ISSUE TITLE
User Task: add a visual representation

### ISSUE THREAD

**Issue by spulci** [zeebe-io/zeebe-modeler#76]
__Is your feature request related to a problem? Please describe.__

A recently released [Job Worker](https://github.com/zeebe-io/zeebe-simple-tasklist) helps to model an user task.  The modeler does not provide a specific User Task XML tag as well as its visual representation actually 

__Describe the solution you'd like__

A button in the modeler that adds an User Task box to your diagram that generates an XML tag like this:

`<bpmn:userTask id="userTask" name="User Task">
  <bpmn:extensionElements>
    <zeebe:taskDefinition type="user" />
    <zeebe:taskHeaders>
      <zeebe:header key="name" value="My User Task" />
      <zeebe:header key="description" value="My first user task with a form field." />
      <zeebe:header key="formFields" value="[{\"key\":\"orderId\", \"label\":\"Order Id\", \"type\":\"string\"}]" />
      <zeebe:header key="assignee" value="demo" />
    </zeebe:taskHeaders>
  </bpmn:extensionElements>
</bpmn:userTask>`

__Describe alternatives you've considered__

Use a service task instead even if it's graphically indistinguishable

**Comment by saig0** [comment]
Hi @spulci,

thank you for raising this up! In order to add user tasks to the modeler palette, Zeebe should support user tasks first. Otherwise, the BPMN would not be parsed. Feel free to open an issue here: https://github.com/zeebe-io/zeebe/issues

**Comment by spulci** [comment]
@saig0 thanks to you. I opened this feature request a few months ago when I was moving first steps with Zeebe. Btw I think that https://github.com/zeebe-io/zeebe-simple-tasklist project should be tested to make it production ready so to add as the official user task implementation. After that we can consider, as you stated before, to add a visual representation of user tasks. I will add an issue to the suggested repo soon, thanks :)

**Comment by nikku** [comment]
Let's close this issue.

As clarified by @saig0 we'll allow the user task once Zeebe supports it (in some way or the other).
