### ISSUE TITLE
I want to know how many versions of the current process are available. What should I do?

### ISSUE THREAD

**Issue by 862618936** [zeebe-io/zeebe-modeler#80]

**Comment by saig0** [comment]
Hi @862618936, please provide more information. It is not clear what do you want to do. 

If you want to see how many versions of a process are deployed to Zeebe then you could use [Operate](https://docs.zeebe.io/operate-user-guide/basic-operate-navigation.html). The Zeebe modeler is just a tool to model processes - it is not an operational tool :)

**Comment by 862618936** [comment]
Hi @saig0 , I mean, how many versions of a process are read through code?no need to Operate!

**Comment by 862618936** [comment]
Hi @saig0  , I mean, how many versions of a process are read through code?no need to Operate!

**Comment by saig0** [comment]
Sorry, I don't get it. What do you mean by "read through code"? 
Please provide an example.

**Comment by 862618936** [comment]
@saig0  Thank you. I know how to solve it

**Comment by saig0** [comment]
Feel free to share your thoughts :)
