### ISSUE TITLE
React client dev start error

### ISSUE THREAD

**Issue by mrkekko92** [zeebe-io/zeebe-modeler#81]
Hi, when I try to open browser webapp (with "npm start" from client folder), I get this error:

![error_zm](https://user-images.githubusercontent.com/52780907/61039530-38eb1900-a3cf-11e9-85b0-219f06ac3cdf.PNG)

Can you tell me the cause of this error and how to solve this problem? Can I boot the client regardless of the destopp app?

**Comment by nikku** [comment]
You cannot boot the client outside of an electron context.

**Comment by mrkekko92** [comment]
Is there a way to use the application from the web? I suppose the application was designed with an electron from a web app, can't we go back to the simple web app?

**Comment by dominikhrn** [comment]
Hi @mrkekko92 ,

I have created a zeebe-modeler webapp a few months ago.
Available here https://github.com/it-economics/zeebe-web-modeler 
There is a lightweight "sync job" that  keeps the zeebe extensions up to date.

**Comment by mrkekko92** [comment]
hi @dominikhrn 
when i execute "npm run dev" this error is shown:

![common](https://user-images.githubusercontent.com/52780907/61212843-ab2b6880-a703-11e9-9e43-10d1ba44a6e0.PNG)

**Comment by dominikhrn** [comment]
Did you execute `npm install`?

**Comment by mrkekko92** [comment]
> Did you execute `npm install`?

yes

**Comment by dominikhrn** [comment]
> > Did you execute `npm install`?
> 
> yes

What is your current npm version?
I guess you should:
- upgrade npm
- clean your npm cache
- delete the node_modules folder
- and run npm install again

**Comment by mrkekko92** [comment]
> > > Did you execute `npm install`?
> > 
> > 
> > yes
> 
> What is your current npm version?
> I guess you should:
> 
> * upgrade npm
> * clean your npm cache
> * delete the node_modules folder
> * and run npm install again

thank you, now I'm trying to figure out how I can edit my xml and see the changes in the diagrams. Do you know a method to access the diagram xml?

**Comment by dominikhrn** [comment]
You can edit your model via drag and drop.
And download it with the "BPMN diagram" button.
There is no xml viewer in that web editor.
Feel free to fork it and adapt it to your requirements.
