### ISSUE TITLE
I can model an interrupting error boundary event

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-modeler#85]
I can attach an interrupting error boundary event. The error boundary event references an error with `name` and `errorCode` as defined in BPMN. No special Zeebe attributes are required.

__Describe the solution you'd like__

* [x] The user is able to create an error interrupting event via the replace menu.

__Additional context__

Inside the `ZeebeModeler` we extend the existing  bpmn-js [`ReplaceMenuProvider`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/popup-menu/ReplaceMenuProvider.js) (cf. [`CustomReplaceMenuProvider`](https://github.com/zeebe-io/zeebe-modeler/blob/master/client/src/app/tabs/bpmn/custom/CustomReplaceMenuProvider.js)) by filtering out all for Zeebe non-available options, which can be find [here](https://github.com/zeebe-io/zeebe-modeler/blob/master/client/src/app/tabs/bpmn/custom/modeler-options/Options.js).

**Comment by pinussilvestrus** [comment]
Closed via 9b88c63b76696b31d2f739713bc33f76db4d2bdb
