### ISSUE TITLE
I can model an event sub process

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-modeler#86]
I can add an event sub process to the diagram. The event sub process can be triggered by the following events:

- Interrupting/Non-Interrupting Message Event (same configuration as intermediate message catch event)
- Interrupting/Non-Interrupting Timer Event (same configuration as intermediate timer event)
- Interrupting Error Event (same configuration as error boundary event #85)

__Describe the solution you'd like__

* [ ] Add event sub process as replace option for normal sub process, Hint: Have a look at the original [`ReplaceMenuProvider`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/popup-menu/ReplaceMenuProvider.js) and the zeebe related [`Options`](https://github.com/zeebe-io/zeebe-modeler/blob/master/client/src/app/tabs/bpmn/custom/modeler-options/Options.js)
* [ ] Add rules for available start events inside an event sub process, Hint: Have a look at how we [distinguish the available options](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/popup-menu/ReplaceMenuProvider.js#L99) for start events inside and outside event sub processes, and decide how to modify the [available options](https://github.com/zeebe-io/zeebe-modeler/blob/master/client/src/app/tabs/bpmn/custom/modeler-options/Options.js) in order to only allow the given possibilities (see above)

**Comment by pinussilvestrus** [comment]
@menski will there be support for Timer and Message StartEvents in Zeebe? Or will they just be able to be created inside an EventSubProcess?

**Comment by Zelldon** [comment]
Hey @pinussilvestrus Zeebe already supports normal Timer and MessageStartEvents :) 
https://docs.zeebe.io/bpmn-workflows/bpmn-coverage.html

**Comment by pinussilvestrus** [comment]
Yeah, already saw it, thanks ;)

**Comment by pinussilvestrus** [comment]
Closed via b621d9d4258eb1fd0b54669139cf7e90d3b0f77b
