### ISSUE TITLE
Create simple download page for nightly builds

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#89]
__Is your feature request related to a problem? Please describe.__

We publish nightly versions of the Zeebe Modeler to [an s3 bucket](https://zeebe-modeler-nightly.s3.eu-central-1.amazonaws.com/). This offers no HTML page to download the nightly versions.

__Describe the solution you'd like__

Build a simple download landing page to download all the different versions inside the bucket.

__Describe alternatives you've considered__

Current workaround: Simply download version via path, e.g.

```sh
$ curl https://zeebe-modeler-nightly.s3.eu-central-1.amazonaws.com/zeebe-modeler-nightly-mac.dmg -O
```

__Additional context__

- [Upload an index file on an s3 bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/HostingWebsiteOnS3Setup.html)

**Comment by pinussilvestrus** [comment]
Simplest sketch: [index.html.txt](https://github.com/zeebe-io/zeebe-modeler/files/3568220/index.html.txt)

**Comment by nikku** [comment]
I've uploaded a download page according to the [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/HostingWebsiteOnS3Setup.html#step1-create-bucket-config-as-website).

Unfortunately I am not able to configure the bucket as a website, which is the requirement for `index.html` files to be shown.

Will investigate on Monday.

**Comment by nikku** [comment]
Closing this as won't fix.
