### ISSUE TITLE
Use 'zeebe' prefix for properties panel entry labels

### ISSUE THREAD

**Issue by pinussilvestrus** [zeebe-io/zeebe-modeler#90]
__Is your feature request related to a problem? Please describe.__

We have a fixed `camunda` prefix for all properties labels and ids, e.g. [for a `TexInputEntry`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/factory/TextInputEntryFactory.js#L41) which results in entries for the `ZeebePropertiesProvider` with this label and id prefix, even they don't belong to the camunda context (cf. screenshot for the task definition type property).

<img width="800" alt="Bildschirmfoto 2019-09-04 um 10 21 34" src="https://user-images.githubusercontent.com/9433996/64238011-d198a380-cefd-11e9-9c7c-83b18af0f061.png">

__Describe the solution you'd like__

Let all the zeebe related entries have a `zeebe` prefix. So in the case of the example screenshot it would look like this: 

```html
<div class="bpp-properties-entry bpp-textfield" data-entry="taskDefinitionType">
  <label for="zeebe-taskDefinitionType">Type</label>
  <div class="bpp-field-wrapper"> 
     <input id="zeebe-taskDefinitionType" type="text" name="type">
      <button class="clear" data-action="clear" data-show="canClear">
        <span>X</span>
      </button>
  </div>
</div>
```

This would need a deep change in [`TextInputEntry`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/factory/TextInputEntryFactory.js#L41) (and all the other entries) to make the prefix customizable.

__Describe alternatives you've considered__

Leave everything as it is.

**Comment by nikku** [comment]
Makes a lot of sense. We should change this as long as we have the freedom to do so.

**Comment by pinussilvestrus** [comment]
One additional thought: We use a couple of original properties inside the [`ZeebePropertiesProvider`](https://github.com/zeebe-io/zeebe-modeler/blob/master/client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js#L17), do we want to have 

* (1) the  `zeebe` prefix for _all_ properties or
* (2) just for the custom zeebe related?

In the second case, it should be enough to make the prefix customizable inside the entry factories, using `camunda` as default and pipe in `zeebe` prefix via options.

```javascript

/// TextInputEntryFactory.js
var prefix = options.prefix || 'camunda',
    inputId = prefix + '-' + escapeHTML(resource.id);

  resource.html =
    '<label for="' + inputId + '" ' +
      /* ... */
    '<div class="bpp-field-wrapper" ' +
     /* ... */
      '<input id="' + inputId + '" type="text" name="' + escapeHTML(options.modelProperty) + '" ' +
    /* ... */
    '</div>';

/// zeebe related property implementation
group.entries.push(entryFactory.textField({
    id: 'foo',
    label: 'Foo',
    modelProperty: 'foo',
    prefix: 'zeebe',
    get: /* ... */,
    set: /* ... */
});
```

In the first option, we would also have to update all property implementations to somehow define the prefix from outside. 

Personally, to make it consistent and clearly seperate the different properties providers, option (1) would be the cleaner way, but would lead to more work.

**Comment by nikku** [comment]
Seems like I missunderstood the namespacing here. 

Why do we assign the Camunda namespace prefix in the first place in the `bpmn-js-properties-panel`? What is the purpose? Which kind of clashes would we like to avoid?

Let's answer these questions before deciding how much work we put into the prefixing.

**Comment by nikku** [comment]
If these prefixes are just used to prevent ID clashes, in that case they could be random, too.

**Comment by pinussilvestrus** [comment]
As I can overview the use of the prefixes I think they only got introduced to prevent ID clashes... One interesting thing is that we use one additional `cam` prefix in the `CamundaPropertiesProvider`, cf. [`ConditionalProps`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/parts/ConditionalProps.js#L33). 

I'm not sure whether they are somehow used in any other place than just querying the fields inside our test case. At first look, it seems do be not the case.

**Comment by nikku** [comment]
What about generating unique ones per properties-panel instance then: 

* `id="{PROPERTIES_PANEL_INSTANCE_ID}_{suffix}"` 

This should be the actual fix. The elements should not be queried by ID anyway but via the `data-entry` attribute.

**Comment by pinussilvestrus** [comment]
Like!

I'll create an issue for that at the `bpmn-js-properties-panel` and move this one to backlog, since it's not that mandatory for now.

**Comment by nikku** [comment]
Let's close this issue then? Should not be fixed here, right?

**Comment by pinussilvestrus** [comment]
oh, yes, no work will be done here.
