### ISSUE TITLE
Remove ability to model collapsed sub-processes

### ISSUE THREAD

**Issue by nikku** [zeebe-io/zeebe-modeler#94]
__Is your feature request related to a problem? Please describe.__

Collapsed sub-processes are considered harmful for process automation, as they hide important execution details from sight.

__Describe the solution you'd like__

* [ ] Remove the ability to model collapsed sub-processes (cf. https://github.com/camunda/camunda-modeler/issues/1486)

__Describe alternatives you've considered__

None. Let's just do this before people start to use these dudes.

---

Related to https://github.com/camunda/camunda-modeler/issues/1486
Depends on https://github.com/zeebe-io/zeebe-modeler/issues/160

**Comment by pinussilvestrus** [comment]
Will be closed once we pull in the [camunda-modeler@3.5](https://github.com/camunda/camunda-modeler/issues/1590) changes.

Cf. https://github.com/camunda/camunda-modeler/commit/a2c008d09effe200c857ec36a20889ae4dde598a + latest diagram-js version.

**Comment by nikku** [comment]
Added the fixed upstream label.

**Comment by pinussilvestrus** [comment]
Depends on #160
